/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientside;


import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author iLLuMinaTi
 */
class InitFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitFrame
     */
    private String servIP;
    private int servPort;
    private final DataExchangeClient checkServer; //it will provide data exchange between login/registerCheckServer
    public InitFrame() {
        //making connection to the server for login and register check
        servIP = "localhost";
        servPort = 2789;  //checkServer Runs at Port 2789
        checkServer = new DataExchangeClient(servIP,servPort);
        
        initComponents();
        signUpPanel.setVisible(false);
        firstNameTextField.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        loginPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginHeaddPanel = new javax.swing.JPanel();
        loginHeadLabel = new javax.swing.JLabel();
        signInPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        creditLabel1 = new javax.swing.JLabel();
        usernameLoginPanel = new javax.swing.JPanel();
        usernameLoginLabel = new javax.swing.JLabel();
        passwordLoginPanel = new javax.swing.JPanel();
        passwordLoginLabel = new javax.swing.JLabel();
        usernameLoginTextField = new javax.swing.JTextField();
        backLoginButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        loginPasswordField = new javax.swing.JPasswordField();
        signUpPanel = new javax.swing.JPanel();
        signUpHeadPanel = new javax.swing.JPanel();
        signUpHeadLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        creditLabel2 = new javax.swing.JLabel();
        firstNamePanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNamePanel = new javax.swing.JPanel();
        lastNameLabel = new javax.swing.JLabel();
        usernameRegisterPanel = new javax.swing.JPanel();
        usernameRegisterLabel = new javax.swing.JLabel();
        passwordRegisterPanel = new javax.swing.JPanel();
        passwordRegisterLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        usernameRegisterTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        backRegisterButton = new javax.swing.JButton();
        registerPasswordField = new javax.swing.JPasswordField();
        cnfPasswordPanel = new javax.swing.JPanel();
        cnfPasswordLabel = new javax.swing.JLabel();
        cnfPasswordField = new javax.swing.JPasswordField();
        initPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        headLabel = new javax.swing.JLabel();
        subHeadLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        contentLabel = new javax.swing.JLabel();
        creditLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GroupOn");
        setPreferredSize(new java.awt.Dimension(1137, 639));
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(0, 153, 153));
        loginPanel.setPreferredSize(new java.awt.Dimension(1137, 610));

        loginHeaddPanel.setBackground(new java.awt.Color(255, 102, 102));

        loginHeadLabel.setFont(new java.awt.Font("Rockney", 0, 30)); // NOI18N
        loginHeadLabel.setText("GroupOn");

        javax.swing.GroupLayout loginHeaddPanelLayout = new javax.swing.GroupLayout(loginHeaddPanel);
        loginHeaddPanel.setLayout(loginHeaddPanelLayout);
        loginHeaddPanelLayout.setHorizontalGroup(
            loginHeaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginHeaddPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(loginHeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        loginHeaddPanelLayout.setVerticalGroup(
            loginHeaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginHeaddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginHeadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        signInPanel.setBackground(new java.awt.Color(0, 255, 51));

        loginLabel.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("User Login");

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        creditLabel1.setFont(new java.awt.Font("StopD", 0, 20)); // NOI18N
        creditLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditLabel1.setText("<html><u>Project By: iLLuMinaTi</u></>");

        usernameLoginPanel.setBackground(new java.awt.Color(186, 171, 204));

        usernameLoginLabel.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        usernameLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLoginLabel.setText("Username :");

        javax.swing.GroupLayout usernameLoginPanelLayout = new javax.swing.GroupLayout(usernameLoginPanel);
        usernameLoginPanel.setLayout(usernameLoginPanelLayout);
        usernameLoginPanelLayout.setHorizontalGroup(
            usernameLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        usernameLoginPanelLayout.setVerticalGroup(
            usernameLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameLoginPanelLayout.createSequentialGroup()
                .addComponent(usernameLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        passwordLoginPanel.setBackground(new java.awt.Color(186, 171, 204));

        passwordLoginLabel.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        passwordLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLoginLabel.setText(" Password :");

        javax.swing.GroupLayout passwordLoginPanelLayout = new javax.swing.GroupLayout(passwordLoginPanel);
        passwordLoginPanel.setLayout(passwordLoginPanelLayout);
        passwordLoginPanelLayout.setHorizontalGroup(
            passwordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        passwordLoginPanelLayout.setVerticalGroup(
            passwordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordLoginLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        usernameLoginTextField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        usernameLoginTextField.setToolTipText("Username");

        backLoginButton.setBackground(new java.awt.Color(255, 153, 51));
        backLoginButton.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        backLoginButton.setText("Back");
        backLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginButtonActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(255, 153, 51));
        loginButton.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginPasswordField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginHeaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 358, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLoginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(loginPasswordField)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginHeaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(creditLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(backLoginButton)
                        .addGap(56, 56, 56))))
        );

        signUpPanel.setBackground(new java.awt.Color(0, 255, 204));
        signUpPanel.setEnabled(false);
        signUpPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        signUpHeadPanel.setBackground(new java.awt.Color(255, 102, 102));

        signUpHeadLabel.setFont(new java.awt.Font("Rockney", 0, 30)); // NOI18N
        signUpHeadLabel.setText("GroupOn");

        javax.swing.GroupLayout signUpHeadPanelLayout = new javax.swing.GroupLayout(signUpHeadPanel);
        signUpHeadPanel.setLayout(signUpHeadPanelLayout);
        signUpHeadPanelLayout.setHorizontalGroup(
            signUpHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpHeadPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(signUpHeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        signUpHeadPanelLayout.setVerticalGroup(
            signUpHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpHeadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signUpHeadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        registerPanel.setBackground(new java.awt.Color(0, 255, 51));

        registerLabel.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText(" User Register");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        creditLabel2.setFont(new java.awt.Font("StopD", 0, 20)); // NOI18N
        creditLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditLabel2.setText("<html><u>Project By: iLLuMinaTi</u></>");

        firstNamePanel.setBackground(new java.awt.Color(186, 171, 204));

        firstNameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstNameLabel.setText("First Name :");

        javax.swing.GroupLayout firstNamePanelLayout = new javax.swing.GroupLayout(firstNamePanel);
        firstNamePanel.setLayout(firstNamePanelLayout);
        firstNamePanelLayout.setHorizontalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        firstNamePanelLayout.setVerticalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lastNamePanel.setBackground(new java.awt.Color(186, 171, 204));

        lastNameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameLabel.setText("Last Name :");

        javax.swing.GroupLayout lastNamePanelLayout = new javax.swing.GroupLayout(lastNamePanel);
        lastNamePanel.setLayout(lastNamePanelLayout);
        lastNamePanelLayout.setHorizontalGroup(
            lastNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lastNamePanelLayout.setVerticalGroup(
            lastNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        usernameRegisterPanel.setBackground(new java.awt.Color(186, 171, 204));

        usernameRegisterLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        usernameRegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameRegisterLabel.setText("Username :");

        javax.swing.GroupLayout usernameRegisterPanelLayout = new javax.swing.GroupLayout(usernameRegisterPanel);
        usernameRegisterPanel.setLayout(usernameRegisterPanelLayout);
        usernameRegisterPanelLayout.setHorizontalGroup(
            usernameRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameRegisterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usernameRegisterPanelLayout.setVerticalGroup(
            usernameRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameRegisterLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        passwordRegisterPanel.setBackground(new java.awt.Color(186, 171, 204));

        passwordRegisterLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        passwordRegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordRegisterLabel.setText("Password :");

        javax.swing.GroupLayout passwordRegisterPanelLayout = new javax.swing.GroupLayout(passwordRegisterPanel);
        passwordRegisterPanel.setLayout(passwordRegisterPanelLayout);
        passwordRegisterPanelLayout.setHorizontalGroup(
            passwordRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordRegisterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passwordRegisterPanelLayout.setVerticalGroup(
            passwordRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordRegisterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        lastNameTextField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N

        usernameRegisterTextField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N

        firstNameTextField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(255, 153, 51));
        registerButton.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        backRegisterButton.setBackground(new java.awt.Color(255, 153, 51));
        backRegisterButton.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        backRegisterButton.setText("Back");
        backRegisterButton.setAutoscrolls(true);
        backRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backRegisterButtonActionPerformed(evt);
            }
        });

        registerPasswordField.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        cnfPasswordPanel.setBackground(new java.awt.Color(186, 171, 204));
        cnfPasswordPanel.setPreferredSize(new java.awt.Dimension(110, 41));
        cnfPasswordPanel.setVerifyInputWhenFocusTarget(false);

        cnfPasswordLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cnfPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cnfPasswordLabel.setText("Confirm Password :");

        javax.swing.GroupLayout cnfPasswordPanelLayout = new javax.swing.GroupLayout(cnfPasswordPanel);
        cnfPasswordPanel.setLayout(cnfPasswordPanelLayout);
        cnfPasswordPanelLayout.setHorizontalGroup(
            cnfPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnfPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cnfPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cnfPasswordPanelLayout.setVerticalGroup(
            cnfPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnfPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cnfPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cnfPasswordField.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addComponent(signUpHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cnfPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(7, 7, 7)))
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cnfPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(registerPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(lastNameTextField)
                            .addComponent(usernameRegisterTextField))))
                .addGap(0, 354, Short.MAX_VALUE))
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addComponent(creditLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(usernameRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usernameRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerPasswordField))
                .addGap(31, 31, 31)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cnfPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(cnfPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addComponent(backRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        initPanel.setBackground(new java.awt.Color(153, 225, 253));
        initPanel.setPreferredSize(new java.awt.Dimension(1117, 610));

        headPanel.setBackground(new java.awt.Color(255, 102, 102));

        headLabel.setFont(new java.awt.Font("Rockney", 0, 70)); // NOI18N
        headLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLabel.setText("<html><u>GroupOn</u></html>");

        subHeadLabel.setFont(new java.awt.Font("Technical", 1, 24)); // NOI18N
        subHeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subHeadLabel.setText("Modern Place for Discussions");
        subHeadLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headLabel)
                    .addComponent(subHeadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                .addGap(291, 291, 291))
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addComponent(headLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(subHeadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginBtn.setBackground(new java.awt.Color(255, 153, 51));
        loginBtn.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        loginBtn.setText("Log Me In ->");
        loginBtn.setToolTipText("");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signUpBtn.setBackground(new java.awt.Color(255, 153, 51));
        signUpBtn.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        signUpBtn.setText("Sign Me Up!!");
        signUpBtn.setToolTipText("");
        signUpBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        contentPanel.setBackground(new java.awt.Color(0, 204, 255));

        contentLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        contentLabel.setText("About GroupOn:");
        contentLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        creditLabel.setFont(new java.awt.Font("StopD", 0, 20)); // NOI18N
        creditLabel.setText("<html><u>Project By: iLLuMinaTi</u></>");

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initPanelLayout.createSequentialGroup()
                        .addComponent(creditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(initPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(initPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(creditLabel))
                .addGap(1183, 1183, 1183))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
            .addComponent(signUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(initPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(325, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        initPanel.setVisible(false);
        loginPanel.setVisible(false);
        signUpPanel.setVisible(true);
        firstNameTextField.requestFocus();
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        initPanel.setVisible(false);
        signUpPanel.setVisible(false);
        loginPanel.setVisible(true);
        usernameLoginTextField.requestFocus();    
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backRegisterButtonActionPerformed
        // TODO add your handling code here:
        initPanel.setVisible(true);
        loginPanel.setVisible(false);
        signUpPanel.setVisible(false);
    }//GEN-LAST:event_backRegisterButtonActionPerformed

    private void backLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginButtonActionPerformed
        initPanel.setVisible(true);
        loginPanel.setVisible(false);
        signUpPanel.setVisible(false);
    }//GEN-LAST:event_backLoginButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String [] data = {"login",usernameLoginTextField.getText(),String.valueOf(loginPasswordField.getPassword())};
        checkServer.send(data);
        String res = checkServer.getData();
        System.err.println("Inside loginBtnAction and res="+res);
        switch (res) {
        //that means null data recieved depicting error in login
            case "IUP":
                System.out.println("Error... Incorrect Username or Password ");
                JOptionPane.showMessageDialog(this,"Incorrect Username or Password","Error..",JOptionPane.ERROR_MESSAGE);
                break;
            case "UDE":
                System.out.println("Error... User Doesn't Exist ");
                JOptionPane.showMessageDialog(this,"Username doesn't exist","Error",JOptionPane.ERROR_MESSAGE);
                break;
        //Login Successful...
            default:
                String uid=res;
                String fName = checkServer.getData();
                String lName = checkServer.getData();
                DashFrame df = new DashFrame(uid,usernameLoginTextField.getText(),fName,lName);
                checkServer.closeConnection();
                df.setVisible(true);
                df.startNotifThread();
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String data[] = {"registerVerify",firstNameTextField.getText(), lastNameTextField.getText(), usernameRegisterTextField.getText(), String.valueOf(registerPasswordField.getPassword())};
        
        
        String x=String.valueOf(registerPasswordField.getPassword());
        String y=String.valueOf(cnfPasswordField.getPassword());
            
        if(x.equals(y)){


            checkServer.send(data);// we will send data after verifying






            String res = checkServer.getData();

            if("ok".equals(res)) //for register verify
            {
                System.out.println("All fields are appropriate.. and now the  entries can be added to data base");

                // to register the user in data base
                String data2[] = {"register",firstNameTextField.getText(), lastNameTextField.getText(), usernameRegisterTextField.getText(), String.valueOf(registerPasswordField.getPassword())};
                checkServer.send(data2);
                String res2 = checkServer.getData();
                if("ok".equals(res2))  //for storing the registered data
                {
                    System.out.println("Registered Successfully..");
                    JOptionPane.showMessageDialog(this,"You have registered succesfully!! \n Please log in to continue..","Ready To Start..", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    //Connection Problem..
                    JOptionPane.showMessageDialog(this,"Connection Problem!!\n Please try again..","Oops...", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Error... res2= "+res2);
                }
            }

            else
            {
                //Registration Errors...
                JOptionPane.showMessageDialog(this,res,"Just A Minute...", JOptionPane.ERROR_MESSAGE);
                //System.out.println("Error... some fields are not appropriate  (received result= )"+res);
            }
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Password and Confirm Passoword do not match","Just a minute...", JOptionPane.INFORMATION_MESSAGE);
              //JOptionPane.showMessageDialog(this,"Password and Confirm Passoword do not match", JOptionPane.ERROR_MESSAGE);
        }
          
        
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLoginButton;
    private javax.swing.JButton backRegisterButton;
    private javax.swing.JPasswordField cnfPasswordField;
    private javax.swing.JLabel cnfPasswordLabel;
    private javax.swing.JPanel cnfPasswordPanel;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JLabel creditLabel1;
    private javax.swing.JLabel creditLabel2;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel headLabel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel initPanel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel lastNamePanel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHeadLabel;
    private javax.swing.JPanel loginHeaddPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JPanel passwordLoginPanel;
    private javax.swing.JLabel passwordRegisterLabel;
    private javax.swing.JPanel passwordRegisterPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signUpHeadLabel;
    private javax.swing.JPanel signUpHeadPanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel subHeadLabel;
    private javax.swing.JLabel usernameLoginLabel;
    private javax.swing.JPanel usernameLoginPanel;
    private javax.swing.JTextField usernameLoginTextField;
    private javax.swing.JLabel usernameRegisterLabel;
    private javax.swing.JPanel usernameRegisterPanel;
    private javax.swing.JTextField usernameRegisterTextField;
    // End of variables declaration//GEN-END:variables
}
