package clientside;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author iLLuMinaTi
 */
public class DashFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashFrame
     */
    DefaultListModel listModel;
    ArrayList<String> arrayList;//stores online users
    ArrayList<String> srchUsrs;
    private String username;
    private String fName;
    private String lName;
    private String uid;
    private Thread notifCheck;
    private String servIP;
    private int servPort;
    private ArrayList<NotificationClient> notifs;
    private final DataExchangeClient dec; //it will provide data exchange between client and DashServer
    
    public DashFrame(String uid,String username,String fName,String lName) {
        this.fName = fName;
        this.lName = lName;
        this.uid=uid;
        this.username = username;

        initComponents();        
        servIP = "localhost";
        servPort = 1221;  //checkServer Runs at Port 1221
        dec = new DataExchangeClient(servIP,servPort);
        dec.send(new String[] {uid,username});
        notifs = new ArrayList<NotificationClient>(); 
        srchUsrs = new ArrayList<String>();
        notifCheck = new Thread( new NotifCheckThread());
        choiceBtnGrp.add(mySpacesBtn);
        choiceBtnGrp.add(createSpaceBtn);
        choiceBtnGrp.add(singleChatBtn);
        choiceBtnGrp.add(settingsBtn);
        choiceBtnGrp.add(notifBtn);
        choiceBtnGrp.add(searchBtn);
        greetLabel.setText("Hello, "+username);
        mySpacesBtn.setSelected(true);
        singleChatPanel.setVisible(false);
        createSpacePanel.setVisible(false);
        settingsPanel.setVisible(false);
        searchPanel.setVisible(false);
        notifPanel.setVisible(false);
        
    }
    
    public void startNotifThread()
    {
        notifCheck.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceBtnGrp = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        dashHeaddPanel = new javax.swing.JPanel();
        loginHeadLabel = new javax.swing.JLabel();
        dpSeparator = new javax.swing.JSeparator();
        logContSeparator = new javax.swing.JSeparator();
        dpMainPanel = new javax.swing.JPanel();
        dpPanel = new javax.swing.JPanel();
        dpScrollPane = new javax.swing.JScrollPane();
        dpTextPane = new javax.swing.JTextPane();
        choicePanel = new javax.swing.JPanel();
        singleChatBtn = new javax.swing.JToggleButton();
        createSpaceBtn = new javax.swing.JToggleButton();
        mySpacesBtn = new javax.swing.JToggleButton();
        settingsBtn = new javax.swing.JToggleButton();
        notifBtn = new javax.swing.JToggleButton();
        mySpacePanel = new javax.swing.JPanel();
        logoutPanel = new javax.swing.JPanel();
        logOutBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        greetPanel = new javax.swing.JPanel();
        greetLabel = new javax.swing.JLabel();
        singleChatPanel = new javax.swing.JPanel();
        onlineUsersScrollPane = new javax.swing.JScrollPane();
        onlineUsersList = new javax.swing.JList<>();
        chatButton = new javax.swing.JButton();
        createSpacePanel = new javax.swing.JPanel();
        notifPanel = new javax.swing.JPanel();
        notifScrollPane = new javax.swing.JScrollPane();
        notifList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchedUsersScrollPane = new javax.swing.JScrollPane();
        searchedUsersList = new javax.swing.JList<>();
        chatNowBtn = new javax.swing.JButton();
        viewProfileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1137, 675));
        setResizable(false);

        MainPanel.setPreferredSize(new java.awt.Dimension(6056, 675));
        MainPanel.setRequestFocusEnabled(false);

        settingsPanel.setBackground(new java.awt.Color(0, 255, 255));
        settingsPanel.setPreferredSize(new java.awt.Dimension(920, 562));

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        dashHeaddPanel.setBackground(new java.awt.Color(255, 102, 102));

        loginHeadLabel.setFont(new java.awt.Font("Rockney", 0, 30)); // NOI18N
        loginHeadLabel.setText("GroupOn");

        javax.swing.GroupLayout dashHeaddPanelLayout = new javax.swing.GroupLayout(dashHeaddPanel);
        dashHeaddPanel.setLayout(dashHeaddPanelLayout);
        dashHeaddPanelLayout.setHorizontalGroup(
            dashHeaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashHeaddPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(loginHeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        dashHeaddPanelLayout.setVerticalGroup(
            dashHeaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashHeaddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginHeadLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dpSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        dpSeparator.setPreferredSize(new java.awt.Dimension(20, 10));

        dpTextPane.setEditable(false);
        dpScrollPane.setViewportView(dpTextPane);

        javax.swing.GroupLayout dpPanelLayout = new javax.swing.GroupLayout(dpPanel);
        dpPanel.setLayout(dpPanelLayout);
        dpPanelLayout.setHorizontalGroup(
            dpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        dpPanelLayout.setVerticalGroup(
            dpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        singleChatBtn.setText("Single Chat");
        singleChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleChatBtnActionPerformed(evt);
            }
        });

        createSpaceBtn.setText("Create Group");
        createSpaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSpaceBtnActionPerformed(evt);
            }
        });

        mySpacesBtn.setText("My Groups");
        mySpacesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySpacesBtnActionPerformed(evt);
            }
        });

        settingsBtn.setText("Settings");
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });

        notifBtn.setText("Notifications");
        notifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choicePanelLayout = new javax.swing.GroupLayout(choicePanel);
        choicePanel.setLayout(choicePanelLayout);
        choicePanelLayout.setHorizontalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSpaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mySpacesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        choicePanelLayout.setVerticalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choicePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(notifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mySpacesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(singleChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createSpaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dpMainPanelLayout = new javax.swing.GroupLayout(dpMainPanel);
        dpMainPanel.setLayout(dpMainPanelLayout);
        dpMainPanelLayout.setHorizontalGroup(
            dpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpMainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dpMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dpMainPanelLayout.setVerticalGroup(
            dpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpMainPanelLayout.createSequentialGroup()
                .addComponent(dpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        mySpacePanel.setBackground(new java.awt.Color(51, 0, 255));
        mySpacePanel.setPreferredSize(new java.awt.Dimension(920, 562));

        javax.swing.GroupLayout mySpacePanelLayout = new javax.swing.GroupLayout(mySpacePanel);
        mySpacePanel.setLayout(mySpacePanelLayout);
        mySpacePanelLayout.setHorizontalGroup(
            mySpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        mySpacePanelLayout.setVerticalGroup(
            mySpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        logOutBtn.setFont(new java.awt.Font("Humanst521 BT", 0, 24)); // NOI18N
        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Humanst521 BT", 0, 18)); // NOI18N

        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        greetLabel.setFont(new java.awt.Font("Humanst521 BT", 0, 24)); // NOI18N
        greetLabel.setText("Hello, User");

        javax.swing.GroupLayout greetPanelLayout = new javax.swing.GroupLayout(greetPanel);
        greetPanel.setLayout(greetPanelLayout);
        greetPanelLayout.setHorizontalGroup(
            greetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(greetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        greetPanelLayout.setVerticalGroup(
            greetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greetPanelLayout.createSequentialGroup()
                .addComponent(greetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(greetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchField)
                        .addComponent(greetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(498, 498, 498))
        );

        singleChatPanel.setBackground(new java.awt.Color(204, 171, 193));
        singleChatPanel.setPreferredSize(new java.awt.Dimension(920, 562));

        onlineUsersList.setBackground(new java.awt.Color(166, 222, 223));
        onlineUsersList.setFont(new java.awt.Font("Humanst521 BT", 0, 22)); // NOI18N
        onlineUsersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        onlineUsersList.setPreferredSize(new java.awt.Dimension(896, 392));
        onlineUsersScrollPane.setViewportView(onlineUsersList);

        chatButton.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        chatButton.setText("Chat Now !");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout singleChatPanelLayout = new javax.swing.GroupLayout(singleChatPanel);
        singleChatPanel.setLayout(singleChatPanelLayout);
        singleChatPanelLayout.setHorizontalGroup(
            singleChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleChatPanelLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(singleChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onlineUsersScrollPane)
                .addContainerGap())
        );
        singleChatPanelLayout.setVerticalGroup(
            singleChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onlineUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        createSpacePanel.setBackground(new java.awt.Color(255, 51, 204));
        createSpacePanel.setPreferredSize(new java.awt.Dimension(920, 562));

        javax.swing.GroupLayout createSpacePanelLayout = new javax.swing.GroupLayout(createSpacePanel);
        createSpacePanel.setLayout(createSpacePanelLayout);
        createSpacePanelLayout.setHorizontalGroup(
            createSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        createSpacePanelLayout.setVerticalGroup(
            createSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        notifPanel.setBackground(new java.awt.Color(255, 255, 102));
        notifPanel.setPreferredSize(new java.awt.Dimension(920, 562));

        notifList.setFont(new java.awt.Font("Humanst521 BT", 0, 18)); // NOI18N
        notifList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        notifScrollPane.setViewportView(notifList);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton1.setText("View");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Mark All as Read");

        javax.swing.GroupLayout notifPanelLayout = new javax.swing.GroupLayout(notifPanel);
        notifPanel.setLayout(notifPanelLayout);
        notifPanelLayout.setHorizontalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(notifScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(notifPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        notifPanelLayout.setVerticalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(notifScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        searchPanel.setBackground(new java.awt.Color(163, 236, 74));
        searchPanel.setPreferredSize(new java.awt.Dimension(920, 562));

        searchedUsersList.setBackground(new java.awt.Color(166, 222, 223));
        searchedUsersList.setFont(new java.awt.Font("Humanst521 BT", 0, 22)); // NOI18N
        searchedUsersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        searchedUsersList.setPreferredSize(new java.awt.Dimension(896, 392));
        searchedUsersScrollPane.setViewportView(searchedUsersList);

        chatNowBtn.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        chatNowBtn.setText("Chat Now !");
        chatNowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatNowBtnActionPerformed(evt);
            }
        });

        viewProfileBtn.setFont(new java.awt.Font("Humanst521 BT", 0, 30)); // NOI18N
        viewProfileBtn.setText("View Profile");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchedUsersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(viewProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(chatNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchedUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(dpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(dashHeaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(mySpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createSpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(logContSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashHeaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(logContSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mySpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mySpacePanel.getAccessibleContext().setAccessibleName("");
        singleChatPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mySpacesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySpacesBtnActionPerformed
        singleChatPanel.setVisible(false);
        createSpacePanel.setVisible(false);
        settingsPanel.setVisible(false);
        notifPanel.setVisible(false);
        mySpacePanel.setVisible(true);
        
    }//GEN-LAST:event_mySpacesBtnActionPerformed

    private void singleChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleChatBtnActionPerformed
        
        mySpacePanel.setVisible(false);
        createSpacePanel.setVisible(false);
        settingsPanel.setVisible(false);
        searchPanel.setVisible(false);
        notifPanel.setVisible(false);
        singleChatPanel.setVisible(true);
        
        

          String[] info={uid};
          dec.send(info);
        
        String[] type={"getOnlineUsers"};
        dec.send(type);
//        ArrayList<String> arrayList = new ArrayList<>();
//        String sign = dec.getData();
//        
//        int flag=0,cnt=0;
//        while(true){
//            cnt++;
//            String msg=dec.getData();
//            if("<>?".equals(msg))
//                break;
//            System.out.println("message = "+msg);
//            flag=1;
//            msg=cnt+": "+msg;
//            arrayList.add(msg);
//        }
//        
//       if(flag==0){
//        DefaultListModel listModel = new DefaultListModel();
//        for (int i = 0; i < arrayList.size(); i++)
//        {
//            listModel.addElement(arrayList.get(i));
//        }
//       onlineUsersList.setModel(listModel);
//       }        
    }//GEN-LAST:event_singleChatBtnActionPerformed

    private void createSpaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSpaceBtnActionPerformed
        mySpacePanel.setVisible(false);
        singleChatPanel.setVisible(false);
        settingsPanel.setVisible(false);
        searchPanel.setVisible(false);
        notifPanel.setVisible(false);
        createSpacePanel.setVisible(true);
    }//GEN-LAST:event_createSpaceBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        mySpacePanel.setVisible(false);
        singleChatPanel.setVisible(false);
        createSpacePanel.setVisible(false);
        searchPanel.setVisible(false);
        notifPanel.setVisible(false);
        settingsPanel.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed

        String selUser = onlineUsersList.getSelectedValue();
        String rName = selUser.substring(selUser.indexOf(" ")+1,selUser.indexOf("("));
        int selectedIndex = onlineUsersList.getSelectedIndex();
        
        arrayList.remove(selectedIndex);
        //Removing the name from current list
        ArrayList<String> newArrList = new ArrayList<String>();                    
        for(int i=0;i<arrayList.size();i++){
            String x=arrayList.get(i);
            x=(i+1)+": "+x;
            newArrList.add(x);
        }
              
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < newArrList.size(); i++)
        {
            listModel.addElement(newArrList.get(i));
        }
        onlineUsersList.setModel(listModel);
        
       //Starting the chat
        ChatFrame cf = new ChatFrame(username,rName,"S"); //'S' means single chat
        cf.startRecvThread();
        cf.setVisible(true);
    }//GEN-LAST:event_chatButtonActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        //During logout, delete the value of des from the arrDes from the DashServer class!!
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void notifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifBtnActionPerformed
        mySpacePanel.setVisible(false);
        singleChatPanel.setVisible(false);
        createSpacePanel.setVisible(false);
        settingsPanel.setVisible(false);
        searchPanel.setVisible(false);
        notifPanel.setVisible(true);
        
        DefaultListModel listModelNew = new DefaultListModel();
        for (int i = notifs.size()-1; i >= 0; i--)
        {
            
            listModelNew.addElement(notifs.get(i));
        }
        notifBtn.setIcon(null);
        notifList.setModel(listModelNew);
       // notifList.setCellRenderer(new MyCellRender());
    }//GEN-LAST:event_notifBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
//        mySpacesBtn.setEnabled(false);
//        singleChatBtn.setEnabled(false);
//        settingsBtn.setEnabled(false);
//        createSpaceBtn.setEnabled(false);
//        notifBtn.setEnabled(false);
        
        mySpacePanel.setVisible(false);
        singleChatPanel.setVisible(false);
        settingsPanel.setVisible(false);
        createSpacePanel.setVisible(false);
        notifPanel.setVisible(false);
        searchPanel.setVisible(true);
        
//        DefaultListModel listModel1 = new DefaultListModel();
//        searchedUsersList.setModel(listModel1);
        dec.send(new String[] {uid});
        
        String[] type={"searchUser",searchField.getText()};
        dec.send(type);
                            
    }//GEN-LAST:event_searchBtnActionPerformed

    private void chatNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatNowBtnActionPerformed
        
        String selUser = searchedUsersList.getSelectedValue();
        //System.out.println("sel User is: " + selUser);
        
        //getting username
        String rName = selUser.substring(0,selUser.indexOf("("));
        int selectedIndex = searchedUsersList.getSelectedIndex();
        
        srchUsrs.remove(selectedIndex);
        //Removing the name from current list
        ArrayList<String> newArrList = new ArrayList<String>();                    
        for(int i=0;i<srchUsrs.size();i++){
            String x=srchUsrs.get(i);
            x=(i+1)+": "+x;
            newArrList.add(x);
        }
              
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < newArrList.size(); i++)
        {
            listModel.addElement(newArrList.get(i));
        }
        searchedUsersList.setModel(listModel);
        
       //Starting the chat
        ChatFrame cf = new ChatFrame(username,rName,"S"); //'S' means single chat
        cf.startRecvThread();
        cf.setVisible(true);
    }//GEN-LAST:event_chatNowBtnActionPerformed
    
    //inner class for notifCheck thread
    
    class NotifCheckThread implements Runnable
    {

        //this thread will listen for notifications, if found, then 
        @Override
        public void run()
        {
            while(true)
            {
                System.out.println("Listening for data from dash server...");
                String type = dec.getData();
                //if notification, then update notification list
                if(type.equals("notification"))
                {
                    String notif = dec.getData();
                    notifBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientside/icoset/newNotif.jpg")));
                    //notifBtn.setBackground(Color.red);
                    notifBtn.setIconTextGap(8);
                    notifs.add(new NotificationClient(notif,true));
                    System.out.println("Notification : " + notif);
                }
                
                
                else if(type.equals("list")) //else update the array list
                {
                    arrayList = new ArrayList<>();
                //    String sign = dec.getData();

                    int flag=0,cnt=0;
                    while(true){
                        //cnt++;
                        String msg=dec.getData();
                        if("<>?".equals(msg))
                            break;
                        System.out.println("message = "+msg);
                        flag=1;
                        //msg=cnt+": "+msg;
                        arrayList.add(msg);
                    }
                    
                    ArrayList<String> newArrList = new ArrayList<String>();
                    
                    for(int i=0;i<arrayList.size();i++){
                        String x=arrayList.get(i);
                        x=(i+1)+": "+x;
                        newArrList.add(x);
                    }
                    
                    if(flag==1){
                        DefaultListModel listModel = new DefaultListModel();
                        for (int i = 0; i < newArrList.size(); i++)
                        {
                            listModel.addElement(newArrList.get(i));
                        }
                        onlineUsersList.setModel(listModel);
                   }        
                }
                
                
                else if(type.equals("search")) //else update the array list
                {                 
                    
                    srchUsrs = new ArrayList<String>();
                    int flag=0,cnt=0;
                    while(true){
                        String msg=dec.getData();
                        if("<>?".equals(msg))
                            break;
                        System.out.println("message = "+msg);
                        flag=1;
                        //msg=cnt+": "+msg;
                        srchUsrs.add(msg);
                    }
                    //If users present...
                    if(flag==1){
                        DefaultListModel listModel = new DefaultListModel();
                        for (int i = 0; i < srchUsrs.size(); i++)
                        {
                            listModel.addElement(srchUsrs.get(i));
                        }
                        searchedUsersList.setModel(listModel);
                   }        
                }
                else if(type.equals("updateNotif"))
                {
                    
                    ArrayList<String> notifArr = new ArrayList<String>();
                    int flag=0;
                    while(true){
                        String msg=dec.getData();
                        if("<>?".equals(msg))
                            break;
                        System.out.println("message = "+msg);
                        flag=1;
                        //msg=cnt+": "+msg;
                        notifArr.add(msg);
                    }
                    //If users present...
                    if(flag==1){
                        DefaultListModel listModel = new DefaultListModel();
                        for (int i = 0; i < notifArr.size(); i++)
                        {
                            listModel.addElement(notifArr.get(i));
                        }
                        
                        notifList.setModel(listModel);
                   }  
                    
                    
                }
                
                
                
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashFrame("uid","UName","FName","LName").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton chatButton;
    private javax.swing.JButton chatNowBtn;
    private javax.swing.ButtonGroup choiceBtnGrp;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JToggleButton createSpaceBtn;
    private javax.swing.JPanel createSpacePanel;
    private javax.swing.JPanel dashHeaddPanel;
    private javax.swing.JPanel dpMainPanel;
    private javax.swing.JPanel dpPanel;
    private javax.swing.JScrollPane dpScrollPane;
    private javax.swing.JSeparator dpSeparator;
    private javax.swing.JTextPane dpTextPane;
    private javax.swing.JLabel greetLabel;
    private javax.swing.JPanel greetPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator logContSeparator;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel loginHeadLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel mySpacePanel;
    private javax.swing.JToggleButton mySpacesBtn;
    private javax.swing.JToggleButton notifBtn;
    private javax.swing.JList<NotificationClient> notifList;
    private javax.swing.JPanel notifPanel;
    private javax.swing.JScrollPane notifScrollPane;
    private static javax.swing.JList<String> onlineUsersList;
    private javax.swing.JScrollPane onlineUsersScrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    private static javax.swing.JList<String> searchedUsersList;
    private javax.swing.JScrollPane searchedUsersScrollPane;
    private javax.swing.JToggleButton settingsBtn;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JToggleButton singleChatBtn;
    private javax.swing.JPanel singleChatPanel;
    private javax.swing.JButton viewProfileBtn;
    // End of variables declaration//GEN-END:variables
}
